### ISSUE TITLE
I can't find a way to build your package

### ISSUE THREAD

**Issue by DraGiuS** [awcurless/linux-zen-hardened-pkgbuild#1]
> ==> Création du paquet linux-zen-hardened 5.0.10.zen.hardened-1 (mar. 30 avril 2019 18:40:16 CEST)
==> Vérification des dépendances pour l’exécution…
==> Vérification des dépendances pour la compilation…
==> Récupération des sources…
  -> Mise à jour du dépôt zen-kernel git
Récupération de origin
  -> config trouvé
  -> 60-linux.hook trouvé
  -> 90-linux.hook trouvé
  -> linux.preset trouvé
==> Validation des fichiers source avec sha256sums…
    zen-kernel ... Ignoré
    config ... Réussite
    60-linux.hook ... Réussite
    90-linux.hook ... Réussite
    linux.preset ... Réussite
==> Vérification des signatures des fichiers sources grâce à gpg…
    zen-kernel git repo ... ÉCHEC (Clé publique inconnue 9D8E84C6C52152F7)
==> ERREUR : Une ou plusieurs signatures PGP n’ont pas pu être vérifiées. >

**Comment by awcurless** [comment]
You will need to import the missing gpg key, running `gpg --recv-keys 9D8E84C6C52152F7` should do the job

**Comment by DraGiuS** [comment]
> You will need to import the missing gpg key, running `gpg --recv-keys 9D8E84C6C52152F7` should do the job

This don't work.. No data from the server.

**Comment by awcurless** [comment]
Try again in a few minutes. The keyservers sometimes take a little while to synchronize

**Comment by DraGiuS** [comment]
Worked now.
